/**
 * Copies contract ABIs from Foundry's `out/` into `src/abis/*.ts` (as `as const`, so
 * viem infers every function name and argument type), deployed addresses from
 * `packages/contracts/deployments/<chainId>.json` into `src/contract-addresses.ts`, and the
 * frozen Founding Pass design table from the art's `designs.json` into
 * `src/founding-pass-designs.ts` (D-043).
 *
 * Run from the repo root: `bun run chain:export-abis` (builds the contracts first).
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { type Address, getAddress, isAddress } from 'viem'
import { SUPPORTED_CHAINS } from '../src/monad-chains'

const CONTRACTS_PACKAGE_URL = new URL('../../contracts/', import.meta.url)
const FOUNDRY_OUT_URL = new URL('out/', CONTRACTS_PACKAGE_URL)
const DEPLOYMENTS_URL = new URL('deployments/', CONTRACTS_PACKAGE_URL)
const ABIS_OUTPUT_URL = new URL('../src/abis/', import.meta.url)
const CONTRACT_ADDRESSES_OUTPUT_URL = new URL('../src/contract-addresses.ts', import.meta.url)
const FOUNDING_PASS_DESIGNS_URL = new URL(
  'art/founding-pass/previews/designs.json',
  CONTRACTS_PACKAGE_URL,
)
const FOUNDING_PASS_DESIGNS_OUTPUT_URL = new URL('../src/founding-pass-designs.ts', import.meta.url)
const FOUNDING_PASS_DESIGN_COUNT = 1000
const FOUNDING_PASS_RARITIES = new Set(['common', 'uncommon', 'rare', 'legendary'])

const EXPORTED_CONTRACTS = [
  { contractName: 'SneakerNft', abiExportName: 'sneakerNftAbi', fileName: 'sneaker-nft-abi.ts' },
  { contractName: 'StrideToken', abiExportName: 'strideTokenAbi', fileName: 'stride-token-abi.ts' },
  {
    contractName: 'SneakerGame',
    abiExportName: 'sneakerGameAbi',
    fileName: 'sneaker-game-abi.ts',
  },
  {
    contractName: 'FoundingPass',
    abiExportName: 'foundingPassAbi',
    fileName: 'founding-pass-abi.ts',
  },
] as const

const DEPLOYED_CONTRACT_KEYS = ['sneakerNft', 'strideToken', 'sneakerGame', 'foundingPass'] as const

type DeployedContractKey = (typeof DEPLOYED_CONTRACT_KEYS)[number]

type DeployedContractAddresses = Record<DeployedContractKey, Address>

type ChainDeployment = { chainId: number; addresses: DeployedContractAddresses }

await exportAbis()
await exportContractAddresses()
await exportFoundingPassDesigns()

async function exportAbis(): Promise<void> {
  await mkdir(ABIS_OUTPUT_URL, { recursive: true })
  for (const { contractName, abiExportName, fileName } of EXPORTED_CONTRACTS) {
    const artifactUrl = new URL(`${contractName}.sol/${contractName}.json`, FOUNDRY_OUT_URL)
    const artifact: unknown = JSON.parse(await readFile(artifactUrl, 'utf8'))
    const abi = readAbiFromArtifact(artifact, contractName)
    const source = [
      `// GENERATED by \`bun run chain:export-abis\` from packages/contracts/out. Do not edit.`,
      `export const ${abiExportName} = ${JSON.stringify(abi, null, 2)} as const`,
      '',
    ].join('\n')
    await writeFile(new URL(fileName, ABIS_OUTPUT_URL), source)
    console.log(`abi: ${contractName} → src/abis/${fileName}`)
  }
}

async function exportContractAddresses(): Promise<void> {
  const supportedChainIds = new Set<number>(SUPPORTED_CHAINS.map((chain) => chain.id))
  const deploymentFileNames = (await readdir(DEPLOYMENTS_URL)).filter((fileName) =>
    fileName.endsWith('.json'),
  )
  const deployments: ChainDeployment[] = []
  for (const fileName of deploymentFileNames) {
    const deploymentJson: unknown = JSON.parse(
      await readFile(new URL(fileName, DEPLOYMENTS_URL), 'utf8'),
    )
    const deployment = parseDeployment(deploymentJson, fileName)
    if (!supportedChainIds.has(deployment.chainId)) {
      console.log(`addresses: skipping ${fileName} (chain ${deployment.chainId} isn't supported)`)
      continue
    }
    deployments.push(deployment)
    console.log(`addresses: chain ${deployment.chainId} from deployments/${fileName}`)
  }
  await writeFile(CONTRACT_ADDRESSES_OUTPUT_URL, buildContractAddressesSource(deployments))
}

/** One line per design, in design-number order. The art's generator is the only source. */
async function exportFoundingPassDesigns(): Promise<void> {
  const designsJson: unknown = JSON.parse(await readFile(FOUNDING_PASS_DESIGNS_URL, 'utf8'))
  if (!Array.isArray(designsJson) || designsJson.length !== FOUNDING_PASS_DESIGN_COUNT) {
    throw new Error(`designs.json must list all ${FOUNDING_PASS_DESIGN_COUNT} designs`)
  }
  const designLines = designsJson.map((designJson: unknown, designIndex) =>
    JSON.stringify(parseFoundingPassDesign(designJson, designIndex + 1)),
  )
  const source = [
    '// GENERATED by `bun run chain:export-abis` from',
    '// packages/contracts/art/founding-pass/previews/designs.json (frozen 2026-10-08). Do not edit.',
    "import type { FoundingPassDesign } from './founding-pass-design'",
    '',
    "export type { FoundingPassDesign, FoundingPassRarity } from './founding-pass-design'",
    '',
    '/** All 1,000 designs; index `n - 1` is design `n`. */',
    'export const FOUNDING_PASS_DESIGNS: readonly FoundingPassDesign[] = [',
    ...designLines.map((designLine) => `  ${designLine},`),
    ']',
    '',
  ].join('\n')
  await writeFile(FOUNDING_PASS_DESIGNS_OUTPUT_URL, source)
  console.log(`designs: ${designLines.length} Founding Pass designs → src/founding-pass-designs.ts`)
}

function parseFoundingPassDesign(designJson: unknown, expectedDesignNumber: number) {
  const fields = toFieldMap(designJson, `design ${expectedDesignNumber}`)
  const layers = toFieldMap(fields.get('layers'), `design ${expectedDesignNumber}'s layers`)
  const optionValueKeys = toFieldMap(
    layers.get('optionValueKeys'),
    `design ${expectedDesignNumber}'s options`,
  )
  const rarity = fields.get('rarity')
  if (fields.get('designNumber') !== expectedDesignNumber) {
    throw new Error(`designs.json is out of order at design ${expectedDesignNumber}`)
  }
  if (typeof rarity !== 'string' || !FOUNDING_PASS_RARITIES.has(rarity)) {
    throw new Error(`design ${expectedDesignNumber} has an unknown rarity`)
  }
  return {
    designNumber: expectedDesignNumber,
    name: readText(fields, 'name', expectedDesignNumber),
    rarity,
    templateKey: readText(layers, 'templateKey', expectedDesignNumber),
    colorFamilyKey: readText(layers, 'colorFamilyKey', expectedDesignNumber),
    colorwayKey: readText(layers, 'colorwayKey', expectedDesignNumber),
    optionValueKeys: Object.fromEntries(
      [...optionValueKeys.keys()].map((slotKey) => [
        slotKey,
        readText(optionValueKeys, slotKey, expectedDesignNumber),
      ]),
    ),
    laceColorKey: readText(layers, 'laceColorKey', expectedDesignNumber),
  }
}

function toFieldMap(value: unknown, description: string): Map<string, unknown> {
  if (typeof value !== 'object' || value === null) {
    throw new Error(`${description} in designs.json is not an object`)
  }
  return new Map(Object.entries(value))
}

function readText(fields: Map<string, unknown>, fieldName: string, designNumber: number): string {
  const value = fields.get(fieldName)
  if (typeof value !== 'string' || value === '') {
    throw new Error(`design ${designNumber} has no ${fieldName} in designs.json`)
  }
  return value
}

function readAbiFromArtifact(artifact: unknown, contractName: string): unknown[] {
  if (
    typeof artifact !== 'object' ||
    artifact === null ||
    !('abi' in artifact) ||
    !Array.isArray(artifact.abi)
  ) {
    throw new Error(`No ABI in the Foundry artifact for ${contractName}. Run \`forge build\`.`)
  }
  return artifact.abi
}

function parseDeployment(deploymentJson: unknown, fileName: string): ChainDeployment {
  if (typeof deploymentJson !== 'object' || deploymentJson === null) {
    throw new Error(`deployments/${fileName} is not a JSON object`)
  }
  const fields = new Map(Object.entries(deploymentJson))
  const chainId = fields.get('chainId')
  if (typeof chainId !== 'number') throw new Error(`deployments/${fileName} has no chainId`)
  const addresses: DeployedContractAddresses = {
    sneakerNft: readDeployedAddress(fields, 'sneakerNft', fileName),
    strideToken: readDeployedAddress(fields, 'strideToken', fileName),
    sneakerGame: readDeployedAddress(fields, 'sneakerGame', fileName),
    foundingPass: readDeployedAddress(fields, 'foundingPass', fileName),
  }
  return { chainId, addresses }
}

function readDeployedAddress(
  fields: Map<string, unknown>,
  contractKey: DeployedContractKey,
  fileName: string,
): Address {
  const address = fields.get(contractKey)
  if (typeof address !== 'string' || !isAddress(address)) {
    throw new Error(`deployments/${fileName} has no valid ${contractKey} address`)
  }
  return getAddress(address)
}

function buildContractAddressesSource(deployments: ChainDeployment[]): string {
  const chainEntries = deployments
    .sort((left, right) => left.chainId - right.chainId)
    .map(({ chainId, addresses }) => {
      const addressLines = DEPLOYED_CONTRACT_KEYS.map(
        (contractKey) => `    ${contractKey}: '${addresses[contractKey]}',`,
      )
      return [`  ${chainId}: {`, ...addressLines, '  },'].join('\n')
    })
  const addressesObject = chainEntries.length === 0 ? '{}' : `{\n${chainEntries.join('\n')}\n}`
  return `import type { Address } from 'viem'
import type { SupportedChainId } from './monad-chains'

export type StrideMonContractAddresses = {
  sneakerNft: Address
  strideToken: Address
  sneakerGame: Address
  foundingPass: Address
}

/**
 * GENERATED by \`bun run chain:export-abis\` from \`packages/contracts/deployments/\`.
 * Do not edit by hand.
 */
export const CONTRACT_ADDRESSES_BY_CHAIN_ID: Partial<
  Record<SupportedChainId, StrideMonContractAddresses>
> = ${addressesObject}
`
}
