// SPDX-License-Identifier: MIT
// Generated by packages/contracts/art/founding-pass/build-founding-pass-art.ts.
// Never edit it by hand: change the art system (art/founding-pass) and rebuild.
pragma solidity 0.8.37;

import {
    InvalidArtIndex,
    OptionLayer,
    OptionValueArt,
    Panel,
    PanelRole,
    TemplateArt
} from "./FoundingPassArtTypes.sol";

/// @title FoundingPassArtData
/// @notice The Founding Pass art system as data, for `FoundingPassArtRenderer`. Coordinates are
/// whole units in the 1000 × 600 Sneaker space, written as SVG path data.
library FoundingPassArtData {
    uint256 internal constant TEMPLATE_COUNT = 10;
    uint256 internal constant COLOR_FAMILY_COUNT = 14;
    uint256 internal constant COLORWAY_COUNT = 10;

    function readTemplateLabel(uint256 templateIndex) internal pure returns (string memory) {
        if (templateIndex == 0) return "Runner";
        if (templateIndex == 1) return "Racer";
        if (templateIndex == 2) return "Trail";
        if (templateIndex == 3) return "Court";
        if (templateIndex == 4) return "Hoop";
        if (templateIndex == 5) return "Chunky";
        if (templateIndex == 6) return "Sock";
        if (templateIndex == 7) return "Skate";
        if (templateIndex == 8) return "Spike";
        if (templateIndex == 9) return "Hiker";
        revert InvalidArtIndex();
    }

    /// @notice The hand-picked name of each template's one Legendary (D-041).
    function readLegendaryName(uint256 templateIndex) internal pure returns (string memory) {
        if (templateIndex == 0) return "Earthshine";
        if (templateIndex == 1) return "Afterglow";
        if (templateIndex == 2) return "Fogbow";
        if (templateIndex == 3) return "Fire Rainbow";
        if (templateIndex == 4) return "Glory";
        if (templateIndex == 5) return "Nacreous";
        if (templateIndex == 6) return "Moonbow";
        if (templateIndex == 7) return "Airglow";
        if (templateIndex == 8) return "Heat Lightning";
        if (templateIndex == 9) return "Sun Pillar";
        revert InvalidArtIndex();
    }

    function readColorFamilyLabel(uint256 colorFamilyIndex) internal pure returns (string memory) {
        if (colorFamilyIndex == 0) return "Ember";
        if (colorFamilyIndex == 1) return "Cherry";
        if (colorFamilyIndex == 2) return "Rose";
        if (colorFamilyIndex == 3) return "Plum";
        if (colorFamilyIndex == 4) return "Cobalt";
        if (colorFamilyIndex == 5) return "Ocean";
        if (colorFamilyIndex == 6) return "Lagoon";
        if (colorFamilyIndex == 7) return "Jade";
        if (colorFamilyIndex == 8) return "Moss";
        if (colorFamilyIndex == 9) return "Lime";
        if (colorFamilyIndex == 10) return "Clay";
        if (colorFamilyIndex == 11) return "Gold";
        if (colorFamilyIndex == 12) return "Chrome";
        if (colorFamilyIndex == 13) return "Prism";
        revert InvalidArtIndex();
    }

    function readColorwayLabel(uint256 colorwayIndex) internal pure returns (string memory) {
        if (colorwayIndex == 0) return "Dawn";
        if (colorwayIndex == 1) return "Day";
        if (colorwayIndex == 2) return "Flare";
        if (colorwayIndex == 3) return "Dusk";
        if (colorwayIndex == 4) return "Night";
        if (colorwayIndex == 5) return "Frost";
        if (colorwayIndex == 6) return "Eclipse";
        if (colorwayIndex == 7) return "Haze";
        if (colorwayIndex == 8) return "Storm";
        if (colorwayIndex == 9) return "Drift";
        revert InvalidArtIndex();
    }

    /// @notice Indexed by `LaceColor`: the attributes show it once a pass is laced.
    function readLaceColorLabel(uint256 laceColorIndex) internal pure returns (string memory) {
        if (laceColorIndex == 0) return "Cream";
        if (laceColorIndex == 1) return "Ink";
        if (laceColorIndex == 2) return "Tonal";
        if (laceColorIndex == 3) return "Lime";
        revert InvalidArtIndex();
    }

    /// @notice An option slot's name, for the attributes (the Runner's first slot is "Side").
    function readOptionSlotLabel(uint256 templateIndex, uint256 slotIndex)
        internal
        pure
        returns (string memory)
    {
        if (templateIndex == 0 && slotIndex == 0) return "Side"; // Runner
        if (templateIndex == 0 && slotIndex == 1) return "Heel"; // Runner
        if (templateIndex == 0 && slotIndex == 2) return "Sole"; // Runner
        if (templateIndex == 1 && slotIndex == 0) return "Upper"; // Racer
        if (templateIndex == 1 && slotIndex == 1) return "Midsole"; // Racer
        if (templateIndex == 1 && slotIndex == 2) return "Heel"; // Racer
        if (templateIndex == 2 && slotIndex == 0) return "Overlay"; // Trail
        if (templateIndex == 2 && slotIndex == 1) return "Guard"; // Trail
        if (templateIndex == 2 && slotIndex == 2) return "Tread"; // Trail
        if (templateIndex == 3 && slotIndex == 0) return "Side"; // Court
        if (templateIndex == 3 && slotIndex == 1) return "Toe"; // Court
        if (templateIndex == 3 && slotIndex == 2) return "Heel"; // Court
        if (templateIndex == 4 && slotIndex == 0) return "Side"; // Hoop
        if (templateIndex == 4 && slotIndex == 1) return "Ankle"; // Hoop
        if (templateIndex == 4 && slotIndex == 2) return "Collar"; // Hoop
        if (templateIndex == 5 && slotIndex == 0) return "Layers"; // Chunky
        if (templateIndex == 5 && slotIndex == 1) return "Midsole"; // Chunky
        if (templateIndex == 5 && slotIndex == 2) return "Heel"; // Chunky
        if (templateIndex == 6 && slotIndex == 0) return "Cuff"; // Sock
        if (templateIndex == 6 && slotIndex == 1) return "Cage"; // Sock
        if (templateIndex == 6 && slotIndex == 2) return "Sole"; // Sock
        if (templateIndex == 7 && slotIndex == 0) return "Side"; // Skate
        if (templateIndex == 7 && slotIndex == 1) return "Foxing"; // Skate
        if (templateIndex == 7 && slotIndex == 2) return "Heel"; // Skate
        if (templateIndex == 8 && slotIndex == 0) return "Side"; // Spike
        if (templateIndex == 8 && slotIndex == 1) return "Support"; // Spike
        if (templateIndex == 8 && slotIndex == 2) return "Plate"; // Spike
        if (templateIndex == 9 && slotIndex == 0) return "Shaft"; // Hiker
        if (templateIndex == 9 && slotIndex == 1) return "Rand"; // Hiker
        if (templateIndex == 9 && slotIndex == 2) return "Collar"; // Hiker
        revert InvalidArtIndex();
    }

    /// @notice An option value's name, for the attributes ("Wedge" in the Runner's "Side").
    function readOptionValueLabel(uint256 templateIndex, uint256 slotIndex, uint256 valueIndex)
        internal
        pure
        returns (string memory)
    {
        if (templateIndex == 0 && slotIndex == 0 && valueIndex == 0) return "Wedge"; // Runner Side
        if (templateIndex == 0 && slotIndex == 0 && valueIndex == 1) return "Zigzag"; // Runner Side
        if (templateIndex == 0 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Runner Side
        if (templateIndex == 0 && slotIndex == 0 && valueIndex == 3) return "Chevron"; // Runner Side
        if (templateIndex == 0 && slotIndex == 1 && valueIndex == 0) return "Counter"; // Runner Heel
        if (templateIndex == 0 && slotIndex == 1 && valueIndex == 1) return "Clip"; // Runner Heel
        if (templateIndex == 0 && slotIndex == 1 && valueIndex == 2) return "Cage"; // Runner Heel
        if (templateIndex == 0 && slotIndex == 2 && valueIndex == 0) return "Plain"; // Runner Sole
        if (templateIndex == 0 && slotIndex == 2 && valueIndex == 1) return "Flash"; // Runner Sole
        if (templateIndex == 0 && slotIndex == 2 && valueIndex == 2) return "Pod"; // Runner Sole
        if (templateIndex == 1 && slotIndex == 0 && valueIndex == 0) return "Streaks"; // Racer Upper
        if (templateIndex == 1 && slotIndex == 0 && valueIndex == 1) return "Block"; // Racer Upper
        if (templateIndex == 1 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Racer Upper
        if (templateIndex == 1 && slotIndex == 0 && valueIndex == 3) return "Shard"; // Racer Upper
        if (templateIndex == 1 && slotIndex == 1 && valueIndex == 0) return "Carbon"; // Racer Midsole
        if (templateIndex == 1 && slotIndex == 1 && valueIndex == 1) return "Tinted"; // Racer Midsole
        if (templateIndex == 1 && slotIndex == 1 && valueIndex == 2) return "Two-tone"; // Racer Midsole
        if (templateIndex == 1 && slotIndex == 2 && valueIndex == 0) return "Plain"; // Racer Heel
        if (templateIndex == 1 && slotIndex == 2 && valueIndex == 1) return "Kick"; // Racer Heel
        if (templateIndex == 1 && slotIndex == 2 && valueIndex == 2) return "Fin"; // Racer Heel
        if (templateIndex == 2 && slotIndex == 0 && valueIndex == 0) return "Ridge"; // Trail Overlay
        if (templateIndex == 2 && slotIndex == 0 && valueIndex == 1) return "Peaks"; // Trail Overlay
        if (templateIndex == 2 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Trail Overlay
        if (templateIndex == 2 && slotIndex == 0 && valueIndex == 3) return "Slope"; // Trail Overlay
        if (templateIndex == 2 && slotIndex == 1 && valueIndex == 0) return "Toe"; // Trail Guard
        if (templateIndex == 2 && slotIndex == 1 && valueIndex == 1) return "Heel"; // Trail Guard
        if (templateIndex == 2 && slotIndex == 1 && valueIndex == 2) return "Rand"; // Trail Guard
        if (templateIndex == 2 && slotIndex == 2 && valueIndex == 0) return "Mono"; // Trail Tread
        if (templateIndex == 2 && slotIndex == 2 && valueIndex == 1) return "Stripe"; // Trail Tread
        if (templateIndex == 2 && slotIndex == 2 && valueIndex == 2) return "Tinted"; // Trail Tread
        if (templateIndex == 3 && slotIndex == 0 && valueIndex == 0) return "Saddle"; // Court Side
        if (templateIndex == 3 && slotIndex == 0 && valueIndex == 1) return "Triangle"; // Court Side
        if (templateIndex == 3 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Court Side
        if (templateIndex == 3 && slotIndex == 0 && valueIndex == 3) return "Chevron"; // Court Side
        if (templateIndex == 3 && slotIndex == 1 && valueIndex == 0) return "Smooth"; // Court Toe
        if (templateIndex == 3 && slotIndex == 1 && valueIndex == 1) return "Cap"; // Court Toe
        if (templateIndex == 3 && slotIndex == 1 && valueIndex == 2) return "Perforated"; // Court Toe
        if (templateIndex == 3 && slotIndex == 2 && valueIndex == 0) return "Plain"; // Court Heel
        if (templateIndex == 3 && slotIndex == 2 && valueIndex == 1) return "Tab"; // Court Heel
        if (templateIndex == 3 && slotIndex == 2 && valueIndex == 2) return "Spoiler"; // Court Heel
        if (templateIndex == 4 && slotIndex == 0 && valueIndex == 0) return "Bolt"; // Hoop Side
        if (templateIndex == 4 && slotIndex == 0 && valueIndex == 1) return "Panel"; // Hoop Side
        if (templateIndex == 4 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Hoop Side
        if (templateIndex == 4 && slotIndex == 0 && valueIndex == 3) return "Wedge"; // Hoop Side
        if (templateIndex == 4 && slotIndex == 1 && valueIndex == 0) return "Plain"; // Hoop Ankle
        if (templateIndex == 4 && slotIndex == 1 && valueIndex == 1) return "Pad"; // Hoop Ankle
        if (templateIndex == 4 && slotIndex == 1 && valueIndex == 2) return "Strap"; // Hoop Ankle
        if (templateIndex == 4 && slotIndex == 2 && valueIndex == 0) return "Plain"; // Hoop Collar
        if (templateIndex == 4 && slotIndex == 2 && valueIndex == 1) return "Tipped"; // Hoop Collar
        if (templateIndex == 4 && slotIndex == 2 && valueIndex == 2) return "Stripe"; // Hoop Collar
        if (templateIndex == 5 && slotIndex == 0 && valueIndex == 0) return "Mudguard"; // Chunky Layers
        if (templateIndex == 5 && slotIndex == 0 && valueIndex == 1) return "Waves"; // Chunky Layers
        if (templateIndex == 5 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Chunky Layers
        if (templateIndex == 5 && slotIndex == 0 && valueIndex == 3) return "Shard"; // Chunky Layers
        if (templateIndex == 5 && slotIndex == 1 && valueIndex == 0) return "Stacked"; // Chunky Midsole
        if (templateIndex == 5 && slotIndex == 1 && valueIndex == 1) return "Solid"; // Chunky Midsole
        if (templateIndex == 5 && slotIndex == 1 && valueIndex == 2) return "Striped"; // Chunky Midsole
        if (templateIndex == 5 && slotIndex == 2 && valueIndex == 0) return "Plain"; // Chunky Heel
        if (templateIndex == 5 && slotIndex == 2 && valueIndex == 1) return "Cap"; // Chunky Heel
        if (templateIndex == 5 && slotIndex == 2 && valueIndex == 2) return "Pod"; // Chunky Heel
        if (templateIndex == 6 && slotIndex == 0 && valueIndex == 0) return "Plain"; // Sock Cuff
        if (templateIndex == 6 && slotIndex == 0 && valueIndex == 1) return "Band"; // Sock Cuff
        if (templateIndex == 6 && slotIndex == 0 && valueIndex == 2) return "Tipped"; // Sock Cuff
        if (templateIndex == 6 && slotIndex == 1 && valueIndex == 0) return "Wrap"; // Sock Cage
        if (templateIndex == 6 && slotIndex == 1 && valueIndex == 1) return "Zigzag"; // Sock Cage
        if (templateIndex == 6 && slotIndex == 1 && valueIndex == 2) return "Plain"; // Sock Cage
        if (templateIndex == 6 && slotIndex == 1 && valueIndex == 3) return "Chevron"; // Sock Cage
        if (templateIndex == 6 && slotIndex == 2 && valueIndex == 0) return "Flat"; // Sock Sole
        if (templateIndex == 6 && slotIndex == 2 && valueIndex == 1) return "Stripe"; // Sock Sole
        if (templateIndex == 6 && slotIndex == 2 && valueIndex == 2) return "Pod"; // Sock Sole
        if (templateIndex == 7 && slotIndex == 0 && valueIndex == 0) return "Shard"; // Skate Side
        if (templateIndex == 7 && slotIndex == 0 && valueIndex == 1) return "Wedge"; // Skate Side
        if (templateIndex == 7 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Skate Side
        if (templateIndex == 7 && slotIndex == 0 && valueIndex == 3) return "Block"; // Skate Side
        if (templateIndex == 7 && slotIndex == 1 && valueIndex == 0) return "Plain"; // Skate Foxing
        if (templateIndex == 7 && slotIndex == 1 && valueIndex == 1) return "Stripe"; // Skate Foxing
        if (templateIndex == 7 && slotIndex == 1 && valueIndex == 2) return "Double"; // Skate Foxing
        if (templateIndex == 7 && slotIndex == 2 && valueIndex == 0) return "Plain"; // Skate Heel
        if (templateIndex == 7 && slotIndex == 2 && valueIndex == 1) return "Patch"; // Skate Heel
        if (templateIndex == 7 && slotIndex == 2 && valueIndex == 2) return "Counter"; // Skate Heel
        if (templateIndex == 8 && slotIndex == 0 && valueIndex == 0) return "Dart"; // Spike Side
        if (templateIndex == 8 && slotIndex == 0 && valueIndex == 1) return "Streaks"; // Spike Side
        if (templateIndex == 8 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Spike Side
        if (templateIndex == 8 && slotIndex == 0 && valueIndex == 3) return "Chevron"; // Spike Side
        if (templateIndex == 8 && slotIndex == 1 && valueIndex == 0) return "None"; // Spike Support
        if (templateIndex == 8 && slotIndex == 1 && valueIndex == 1) return "Counter"; // Spike Support
        if (templateIndex == 8 && slotIndex == 1 && valueIndex == 2) return "Strap"; // Spike Support
        if (templateIndex == 8 && slotIndex == 2 && valueIndex == 0) return "Matched"; // Spike Plate
        if (templateIndex == 8 && slotIndex == 2 && valueIndex == 1) return "Contrast"; // Spike Plate
        if (templateIndex == 8 && slotIndex == 2 && valueIndex == 2) return "Flash"; // Spike Plate
        if (templateIndex == 9 && slotIndex == 0 && valueIndex == 0) return "Zigzag"; // Hiker Shaft
        if (templateIndex == 9 && slotIndex == 0 && valueIndex == 1) return "Panel"; // Hiker Shaft
        if (templateIndex == 9 && slotIndex == 0 && valueIndex == 2) return "Plain"; // Hiker Shaft
        if (templateIndex == 9 && slotIndex == 0 && valueIndex == 3) return "Peaks"; // Hiker Shaft
        if (templateIndex == 9 && slotIndex == 1 && valueIndex == 0) return "None"; // Hiker Rand
        if (templateIndex == 9 && slotIndex == 1 && valueIndex == 1) return "Heel"; // Hiker Rand
        if (templateIndex == 9 && slotIndex == 1 && valueIndex == 2) return "Wrap"; // Hiker Rand
        if (templateIndex == 9 && slotIndex == 2 && valueIndex == 0) return "Plain"; // Hiker Collar
        if (templateIndex == 9 && slotIndex == 2 && valueIndex == 1) return "Tipped"; // Hiker Collar
        if (templateIndex == 9 && slotIndex == 2 && valueIndex == 2) return "Stripe"; // Hiker Collar
        revert InvalidArtIndex();
    }

    /// @notice A family's five shades, light to dark, as 0xRRGGBB.
    function readShadeColors(uint256 colorFamilyIndex) internal pure returns (uint24[5] memory) {
        if (colorFamilyIndex == 0) {
            return [uint24(0xFFE6CF), 0xFFB27A, 0xFF6F2E, 0xC9431A, 0x6E2310]; // Ember
        }
        if (colorFamilyIndex == 1) {
            return [uint24(0xFFDADF), 0xFF8A96, 0xE8283F, 0xA3122A, 0x5A0A1A]; // Cherry
        }
        if (colorFamilyIndex == 2) {
            return [uint24(0xFFE0F0), 0xFFA3D1, 0xF2559F, 0xB52A72, 0x61163F]; // Rose
        }
        if (colorFamilyIndex == 3) {
            return [uint24(0xEDE0FF), 0xC3A1FF, 0x8C55F0, 0x5C2DB0, 0x2F175F]; // Plum
        }
        if (colorFamilyIndex == 4) {
            return [uint24(0xDFE4FF), 0x9AA8FF, 0x3A50FF, 0x1E2DB8, 0x111A63]; // Cobalt
        }
        if (colorFamilyIndex == 5) {
            return [uint24(0xD9F0FF), 0x8FD0FF, 0x2E9BEA, 0x1A62A8, 0x0F3260]; // Ocean
        }
        if (colorFamilyIndex == 6) {
            return [uint24(0xD5FAF4), 0x7FE6D6, 0x19B5A5, 0x0E7A72, 0x08403F]; // Lagoon
        }
        if (colorFamilyIndex == 7) {
            return [uint24(0xDDF7E3), 0x8EE0A6, 0x2FB863, 0x1A7A42, 0x0D4124]; // Jade
        }
        if (colorFamilyIndex == 8) {
            return [uint24(0xEEF0D8), 0xC9CF94, 0x8E9A4A, 0x5C6630, 0x333A1A]; // Moss
        }
        if (colorFamilyIndex == 9) {
            return [uint24(0xF1FFC4), 0xC1FF00, 0x8FCC00, 0x557A00, 0x2E4206]; // Lime
        }
        if (colorFamilyIndex == 10) {
            return [uint24(0xF5E8D8), 0xDDBB94, 0xB3824F, 0x7A5130, 0x45291A]; // Clay
        }
        if (colorFamilyIndex == 11) {
            return [uint24(0xFFE98A), 0xFFC928, 0xDE9E00, 0xA26A00, 0x5C3C00]; // Gold
        }
        if (colorFamilyIndex == 12) {
            return [uint24(0xE9EEF5), 0xB9C5D6, 0x8391A8, 0x4E596D, 0x262B36]; // Chrome
        }
        if (colorFamilyIndex == 13) {
            return [uint24(0xFFE45C), 0x5CF0C0, 0xFF6AB8, 0x7C4DFF, 0x24196E]; // Prism
        }
        revert InvalidArtIndex();
    }

    /// @notice Gold and Chrome: the families with a flat sheen on the toe and heel.
    function hasSheen(uint256 colorFamilyIndex) internal pure returns (bool) {
        return colorFamilyIndex == 11 || colorFamilyIndex == 12;
    }

    /// @notice The colour of a metallic family's sheen shards.
    function readSheenColor(uint256 colorFamilyIndex) internal pure returns (uint24) {
        if (colorFamilyIndex == 11) return 0xFFFBE6; // Gold
        if (colorFamilyIndex == 12) return 0xFFFFFF; // Chrome
        revert InvalidArtIndex();
    }

    /// @notice Which of the family's shades (0 lightest, 4 darkest) each shaded role takes,
    /// indexed by `PanelRole`.
    /// @dev Columns: Upper, Toe, Overlay, Heel, Eyestay, Collar, Tongue, Trim, SoleAccent, Outsole.
    function readColorwayShadeIndexes(uint256 colorwayIndex)
        internal
        pure
        returns (uint8[10] memory)
    {
        if (colorwayIndex == 0) return [uint8(0), 1, 2, 1, 2, 3, 1, 3, 2, 3]; // Dawn
        if (colorwayIndex == 1) return [uint8(1), 0, 3, 3, 4, 4, 0, 2, 2, 4]; // Day
        if (colorwayIndex == 2) return [uint8(2), 1, 4, 4, 4, 4, 1, 0, 2, 4]; // Flare
        if (colorwayIndex == 3) return [uint8(3), 2, 1, 4, 1, 4, 2, 0, 1, 4]; // Dusk
        if (colorwayIndex == 4) return [uint8(4), 3, 2, 3, 2, 3, 2, 1, 2, 3]; // Night
        if (colorwayIndex == 5) return [uint8(0), 0, 2, 2, 3, 3, 0, 4, 2, 3]; // Frost
        if (colorwayIndex == 6) return [uint8(0), 4, 4, 4, 4, 4, 0, 2, 2, 4]; // Eclipse
        if (colorwayIndex == 7) return [uint8(2), 1, 0, 1, 3, 4, 0, 3, 1, 4]; // Haze
        if (colorwayIndex == 8) return [uint8(2), 4, 1, 4, 3, 4, 1, 0, 2, 4]; // Storm
        if (colorwayIndex == 9) return [uint8(1), 4, 2, 0, 4, 3, 0, 3, 2, 4]; // Drift
        revert InvalidArtIndex();
    }

    function readTemplateArt(uint256 templateIndex) internal pure returns (TemplateArt memory) {
        if (templateIndex == 0) return readRunnerArt();
        if (templateIndex == 1) return readRacerArt();
        if (templateIndex == 2) return readTrailArt();
        if (templateIndex == 3) return readCourtArt();
        if (templateIndex == 4) return readHoopArt();
        if (templateIndex == 5) return readChunkyArt();
        if (templateIndex == 6) return readSockArt();
        if (templateIndex == 7) return readSkateArt();
        if (templateIndex == 8) return readSpikeArt();
        if (templateIndex == 9) return readHikerArt();
        revert InvalidArtIndex();
    }

    function readOptionValue(uint256 templateIndex, uint256 slotIndex, uint256 valueIndex)
        internal
        pure
        returns (OptionValueArt memory)
    {
        if (templateIndex == 0) return readRunnerOptionValue(slotIndex, valueIndex);
        if (templateIndex == 1) return readRacerOptionValue(slotIndex, valueIndex);
        if (templateIndex == 2) return readTrailOptionValue(slotIndex, valueIndex);
        if (templateIndex == 3) return readCourtOptionValue(slotIndex, valueIndex);
        if (templateIndex == 4) return readHoopOptionValue(slotIndex, valueIndex);
        if (templateIndex == 5) return readChunkyOptionValue(slotIndex, valueIndex);
        if (templateIndex == 6) return readSockOptionValue(slotIndex, valueIndex);
        if (templateIndex == 7) return readSkateOptionValue(slotIndex, valueIndex);
        if (templateIndex == 8) return readSpikeOptionValue(slotIndex, valueIndex);
        if (templateIndex == 9) return readHikerOptionValue(slotIndex, valueIndex);
        revert InvalidArtIndex();
    }

    /// @dev The Runner. The everyday trainer: a medium sole, a padded collar and a rounded toe.
    function readRunnerArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M100 520 76 510 64 488 62 460 66 420 58 380 60 330 70 282 86 240 110 224 150 226 196 244 238 258 282 250 312 226 326 192 350 168 386 166 404 184 410 202 688 318 760 338 828 354 880 372 914 394 934 422 938 452 930 476 910 496 872 510 806 518 740 520Z";
        templateArt.silhouetteTopY = 166;
        templateArt.heelTabPathData = "M79 290 52 217 58 202 84 192 98 200 124 273Z";
        templateArt.heelTabMarkPathData = "M71 235 78 217 95 226 99 236 82 226 74 245Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M300 120 450 120 450 230 330 290 300 280Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 140 156 226 206 316 214 440 0 440Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M400 140 750 290 670 362 392 246Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M716 280 1000 280 1000 470 680 470 688 372Z");
        templateArt.framingPanels[3] = Panel(
            PanelRole.Collar,
            "M30 120 346 120 342 214 322 258 288 286 238 296 190 282 112 262 74 280 30 280Z"
        );
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] =
            Panel(PanelRole.Midsole, "M0 412 260 424 1000 446 1000 600 0 600Z");
        templateArt.solePanels[1] =
            Panel(PanelRole.Outsole, "M0 486 680 488 840 482 920 470 1000 448 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M800 362 834 370 782 452 750 452ZM86 292 104 290 90 400 72 402Z";
        templateArt.laceSlatPathData =
            "M428 196 448 205 425 260 405 252ZM474 216 494 224 471 280 451 271ZM520 235 541 243 518 299 497 290ZM567 254 587 263 564 318 544 310ZM613 274 633 282 610 338 590 329ZM659 293 680 301 657 357 636 348Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"01A700EC01D500FF020401120232012602600139028F014C";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Runner: Side (Wedge, Zigzag, Plain, Chevron), Heel (Counter, Clip, Cage), Sole (Plain, Flash, Pod).
    function readRunnerOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Side: Wedge
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M214 300 600 410 214 430Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Side: Zigzag
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Overlay,
                "M214 440 214 368 282 398 350 356 418 394 486 352 554 390 622 358 690 392 690 440Z"
            );
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Side: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Side: Chevron
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M256 300 346 300 452 368 346 436 256 436 336 368Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Heel: Counter
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Heel: Clip
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 330 150 352 184 440 40 440Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Heel: Cage
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Trim, "M30 286 130 296 216 446 30 446ZM64 336 64 414 150 414Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Sole: Plain
            optionValue.layer = OptionLayer.Sole;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Sole: Flash
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M96 440 860 458 800 474 96 466Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Sole: Pod
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M40 420 330 432 230 490 40 490Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Racer. A race-day shoe: a tall rocker sole with a plate, a bevelled heel, a pointed toe.
    function readRacerArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M220 520 150 512 96 494 62 466 54 440 60 414 70 404 78 350 88 302 100 268 128 254 170 258 212 272 250 278 288 266 314 246 328 222 350 206 380 206 394 220 398 236 650 320 740 340 830 360 900 384 940 410 952 432 944 450 930 466 880 488 800 506 700 516 620 520Z";
        templateArt.silhouetteTopY = 206;
        templateArt.heelTabPathData = "M90 313 68 238 75 224 102 216 115 225 136 300Z";
        templateArt.heelTabMarkPathData = "M86 258 94 240 111 251 113 261 97 250 88 268Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M312 150 432 150 432 250 340 300 312 290Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 200 140 256 180 330 176 420 0 420Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M392 176 712 282 636 362 384 278Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M690 292 1000 292 1000 450 640 450 660 364Z");
        templateArt.framingPanels[3] = Panel(
            PanelRole.Collar,
            "M40 170 360 170 352 238 322 262 292 290 252 300 212 294 168 280 126 276 96 296 40 296Z"
        );
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] = Panel(
            PanelRole.Midsole, "M0 410 300 420 620 432 820 424 930 408 1000 396 1000 600 0 600Z"
        );
        templateArt.solePanels[1] = Panel(
            PanelRole.Outsole,
            "M0 494 620 494 720 490 820 478 900 456 960 434 1000 424 1000 600 0 600Z"
        );
        templateArt.sheenPathData =
        "M786 360 818 368 784 414 760 414ZM94 300 110 296 102 380 86 382Z";
        templateArt.laceSlatPathData =
            "M417 230 437 236 418 293 398 286ZM467 246 488 253 469 310 448 303ZM517 263 538 270 519 327 498 320ZM568 280 589 287 570 344 549 337ZM618 297 639 304 620 361 599 354Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"019F010D01D1011E0204012F0236013F02690150";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Racer: Upper (Streaks, Block, Plain, Shard), Midsole (Carbon, Tinted, Two-tone), Heel (Plain, Kick, Fin).
    function readRacerOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Upper: Streaks
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M176 290 560 356 176 366ZM176 380 650 410 176 424Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Upper: Block
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M180 410 180 300 300 300 520 420Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Upper: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Upper: Shard
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M176 300 430 300 176 420Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Midsole: Carbon
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Ink,
                "M110 450 300 456 600 464 800 456 900 438 940 426 936 440 900 452 800 470 600 478 300 470 110 464Z"
            );
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Midsole: Tinted
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.SoleAccent,
                "M110 450 300 456 600 464 800 456 900 438 940 426 936 440 900 452 800 470 600 478 300 470 110 464Z"
            );
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Midsole: Two-tone
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.SoleAccent,
                "M0 410 300 420 620 432 820 424 930 408 1000 396 1000 428 930 440 820 452 620 460 300 448 0 440Z"
            );
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Heel: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Heel: Kick
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M0 410 180 416 150 500 0 500Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Heel: Fin
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M60 300 168 404 40 404Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Trail. Built for dirt: a lugged outsole, a rubber toe bumper and a tough upper.
    function readTrailArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M124 516 96 506 76 490 66 466 62 430 60 390 64 330 76 280 92 240 118 222 160 226 204 244 246 256 288 246 318 220 330 188 354 164 390 162 408 180 414 198 676 310 744 326 812 340 870 358 912 382 936 414 944 448 940 474 928 494 904 508 880 516 872 520 826 520 820 505 812 505 806 520 760 520 754 505 746 505 740 520 694 520 688 505 680 505 674 520 628 520 622 505 614 505 608 520 562 520 556 505 548 505 542 520 496 520 490 505 482 505 476 520 430 520 424 505 416 505 410 520 364 520 358 505 350 505 344 520 298 520 292 505 284 505 278 520 232 520 226 505 218 505 212 520 166 520Z";
        templateArt.silhouetteTopY = 162;
        templateArt.heelTabPathData = "M87 288 60 215 66 200 92 190 106 198 132 271Z";
        templateArt.heelTabMarkPathData = "M79 233 86 215 103 224 107 234 90 224 82 243Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M300 120 450 120 450 230 330 290 300 280Z");
        templateArt.framingPanels = new Panel[](5);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 140 160 228 206 318 214 440 0 440Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M406 140 740 280 658 352 396 240Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M720 290 1000 290 1000 460 690 460 690 380Z");
        templateArt.framingPanels[3] =
            Panel(PanelRole.Trim, "M880 352 1000 352 1000 470 780 470 830 420Z");
        templateArt.framingPanels[4] = Panel(
            PanelRole.Collar,
            "M30 120 346 120 342 210 322 252 288 280 246 292 200 280 116 260 76 278 30 278Z"
        );
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] =
            Panel(PanelRole.Midsole, "M0 410 300 422 1000 440 1000 600 0 600Z");
        templateArt.solePanels[1] =
            Panel(PanelRole.Outsole, "M0 474 700 478 860 474 1000 456 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M790 340 822 346 790 400 760 400ZM92 290 110 288 98 396 80 398Z";
        templateArt.laceSlatPathData =
            "M430 192 451 201 427 256 407 247ZM474 211 494 219 471 274 451 266ZM518 229 538 238 514 293 494 284ZM561 248 582 257 558 312 538 303ZM605 267 625 275 602 330 582 322ZM649 285 669 294 645 349 625 340Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"01AA00E701D500FA0201010D022D011F0258013202840145";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Trail: Overlay (Ridge, Peaks, Plain, Slope), Guard (Toe, Heel, Rand), Tread (Mono, Stripe, Tinted).
    function readTrailOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Overlay: Ridge
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Overlay,
                "M214 450 214 396 250 360 280 392 320 340 360 390 400 350 440 392 480 344 520 390 560 356 600 394 640 360 690 400 690 450Z"
            );
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Overlay: Peaks
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M214 440 300 320 386 440ZM360 440 470 290 580 440Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Overlay: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Overlay: Slope
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M214 440 690 330 690 440Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Guard: Toe
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Guard: Heel
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 352 172 374 214 440 40 440Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Guard: Rand
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M0 384 300 396 1000 414 1000 470 0 470Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Tread: Mono
            optionValue.layer = OptionLayer.Sole;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Tread: Stripe
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M0 432 860 450 830 460 0 444Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Tread: Tinted
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.SoleAccent, "M0 474 700 478 860 474 1000 456 1000 600 0 600Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Court. A clean, low court classic on a tall flat cupsole.
    function readCourtArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M80 520 64 506 60 480 60 430 60 390 64 350 74 314 88 288 116 276 160 280 210 294 250 300 290 290 318 272 332 246 356 230 390 228 406 242 412 258 660 344 740 360 810 370 866 380 906 396 930 418 940 442 940 470 936 494 922 510 880 520Z";
        templateArt.silhouetteTopY = 228;
        templateArt.heelTabPathData = "M78 333 60 257 66 243 93 236 106 245 125 321Z";
        templateArt.heelTabMarkPathData = "M76 278 85 260 101 271 104 281 87 270 78 287Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M316 190 450 190 450 290 340 340 316 330Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 230 150 276 176 340 186 430 0 430Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M406 200 720 310 646 386 398 300Z");
        templateArt.framingPanels[2] = Panel(PanelRole.Toe, "M716 320 1000 320 1000 440 680 440Z");
        templateArt.framingPanels[3] = Panel(
            PanelRole.Collar,
            "M40 220 360 220 352 266 326 288 292 314 250 322 206 316 158 304 112 304 80 324 40 324Z"
        );
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] = Panel(PanelRole.Midsole, "M0 424 1000 428 1000 600 0 600Z");
        templateArt.solePanels[1] = Panel(PanelRole.Outsole, "M0 502 1000 502 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M780 372 812 376 772 426 744 426ZM90 330 108 326 100 418 82 420Z";
        templateArt.laceSlatPathData =
            "M430 252 451 259 431 316 411 308ZM480 269 501 276 481 333 460 326ZM530 286 550 293 531 350 510 343ZM579 303 600 310 580 367 559 360ZM629 320 650 328 630 384 609 377Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"01AC012301DE0134020F01460241015702730168";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Court: Side (Saddle, Triangle, Plain, Chevron), Toe (Smooth, Cap, Perforated), Heel (Plain, Tab, Spoiler).
    function readCourtOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Side: Saddle
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M350 270 480 310 452 440 322 440Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Side: Triangle
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M186 314 186 430 540 430Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Side: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Side: Chevron
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M230 322 320 322 420 382 320 442 230 442 330 382Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Toe: Smooth
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Toe: Cap
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M846 360 1000 360 1000 440 800 440Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Toe: Perforated
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Ink,
                "M764 380 772 372 780 380 772 388ZM804 384 812 376 820 384 812 392ZM844 390 852 382 860 390 852 398ZM780 406 788 398 796 406 788 414ZM820 410 828 402 836 410 828 418ZM860 416 868 408 876 416 868 424Z"
            );
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Heel: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Heel: Tab
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 292 122 300 128 354 40 354Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Heel: Spoiler
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 290 116 296 128 430 40 430Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Hoop. A basketball high-top: a padded ankle collar, a long lace run, a thick cupsole.
    function readHoopArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M90 520 70 508 62 484 64 446 58 400 56 340 60 270 66 200 76 140 92 112 130 100 180 102 222 112 246 128 262 108 280 90 312 80 340 84 352 100 354 118 650 320 720 346 800 364 864 380 906 400 932 428 940 458 936 482 920 500 888 512 830 518 760 520Z";
        templateArt.silhouetteTopY = 80;
        templateArt.heelTabPathData = "M73 162 60 85 68 71 95 66 107 76 121 153Z";
        templateArt.heelTabMarkPathData = "M75 106 85 89 100 102 102 112 87 99 77 116Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M230 30 400 30 400 150 300 220 230 200Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 300 140 316 196 360 206 450 0 450Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M350 60 700 290 624 358 328 156Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M690 316 1000 316 1000 460 670 460 676 390Z");
        templateArt.framingPanels[3] =
            Panel(PanelRole.Collar, "M30 20 290 20 262 120 240 150 190 140 130 142 84 160 30 166Z");
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] = Panel(PanelRole.Midsole, "M0 428 1000 448 1000 600 0 600Z");
        templateArt.solePanels[1] =
            Panel(PanelRole.Outsole, "M0 496 760 498 900 490 1000 470 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M780 366 812 372 772 440 742 440ZM84 200 102 196 96 300 78 302Z";
        templateArt.laceSlatPathData =
            "M373 116 391 129 357 178 339 166ZM415 145 433 158 399 207 381 195ZM457 174 476 186 442 236 424 224ZM500 203 518 215 484 265 466 252ZM542 232 560 244 526 294 508 281ZM584 261 602 273 569 323 550 310ZM627 289 645 302 611 351 593 339Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"0168009A019300B701BD00D401E700F00212010D023C012A02660147";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Hoop: Side (Bolt, Panel, Plain, Wedge), Ankle (Plain, Pad, Strap), Collar (Plain, Tipped, Stripe).
    function readHoopOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Side: Bolt
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Overlay, "M300 220 420 220 370 300 450 300 290 446 336 340 250 340Z"
            );
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Side: Panel
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M0 180 300 150 440 450 0 450Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Side: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Side: Wedge
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M206 330 620 444 206 446Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Ankle: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Ankle: Pad
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Trim, "M112 182 206 178 236 224 206 268 112 272 86 226Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Ankle: Strap
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](2);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 252 322 196 334 246 40 304Z");
            optionValue.panels[1] = Panel(PanelRole.Ink, "M272 214 304 208 312 240 280 246Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Collar: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Collar: Tipped
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Trim, "M30 20 290 20 276 124 220 128 130 120 30 130Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Collar: Stripe
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M30 124 282 84 288 110 30 152Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Chunky. The "dad shoe": a tall layered midsole, a bulky upper, overlays on overlays.
    function readChunkyArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M110 520 84 512 66 492 58 460 60 420 62 380 58 320 64 270 80 226 110 208 156 210 204 228 250 240 292 230 322 204 334 172 360 148 400 146 420 166 426 186 664 280 740 290 812 302 872 322 916 350 944 386 954 428 952 466 942 492 918 510 870 518 800 520Z";
        templateArt.silhouetteTopY = 146;
        templateArt.heelTabPathData = "M77 274 48 202 52 187 78 176 92 184 121 256Z";
        templateArt.heelTabMarkPathData = "M67 220 73 201 91 210 95 219 77 210 70 229Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M310 100 460 100 460 220 350 290 310 270Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 140 150 212 196 300 206 400 0 400Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M420 130 724 250 646 325 408 231Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M704 260 1000 260 1000 420 690 420 670 334Z");
        templateArt.framingPanels[3] = Panel(
            PanelRole.Collar,
            "M30 120 346 120 342 196 322 240 290 268 250 280 200 270 150 254 110 254 74 274 30 274Z"
        );
        templateArt.solePanels = new Panel[](3);
        templateArt.solePanels[0] = Panel(
            PanelRole.Midsole,
            "M0 380 170 384 220 350 300 354 350 374 510 378 560 344 650 348 700 372 1000 384 1000 600 0 600Z"
        );
        templateArt.solePanels[1] = Panel(
            PanelRole.SoleAccent, "M0 440 170 436 210 452 380 446 420 462 1000 452 1000 600 0 600Z"
        );
        templateArt.solePanels[2] = Panel(PanelRole.Outsole, "M0 492 1000 488 1000 600 0 600Z");
        templateArt.sheenPathData = "M790 300 824 306 774 372 742 372ZM80 270 98 266 92 370 74 372Z";
        templateArt.laceSlatPathData =
            "M440 179 460 187 438 243 418 234ZM480 194 500 202 478 258 458 250ZM519 210 540 218 518 274 497 266ZM559 226 579 234 557 290 537 281ZM599 241 619 249 597 305 577 297ZM638 257 659 265 637 321 616 313Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"01B400DA01DC00EA020400F9022B010902530119027B0128";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Chunky: Layers (Mudguard, Waves, Plain, Shard), Midsole (Stacked, Solid, Striped), Heel (Plain, Cap, Pod).
    function readChunkyOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Layers: Mudguard
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M0 316 300 324 1000 340 1000 420 0 420Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Layers: Waves
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Overlay,
                "M196 400 196 330 260 300 320 336 380 296 440 330 500 290 560 324 620 290 690 330 690 400Z"
            );
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Layers: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Layers: Shard
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M196 290 540 400 196 400Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Midsole: Stacked
            optionValue.layer = OptionLayer.Sole;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Midsole: Solid
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](2);
            optionValue.panels[0] = Panel(PanelRole.Midsole, "M0 430 1000 430 1000 600 0 600Z");
            optionValue.panels[1] = Panel(PanelRole.Outsole, "M0 492 1000 488 1000 600 0 600Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Midsole: Striped
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Trim, "M0 404 300 408 1000 414 1000 430 300 424 0 420Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Heel: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Heel: Cap
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 214 126 216 176 272 40 290Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Heel: Pod
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 296 160 316 206 400 40 400Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Sock. A knit sock runner: a tall stretch cuff and no separate tongue.
    function readSockArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M100 520 76 508 64 486 62 452 60 400 62 340 70 270 80 200 92 150 120 140 170 136 222 132 256 136 274 156 300 196 660 320 740 342 810 358 868 376 908 398 932 426 938 456 930 480 912 498 876 510 810 518 740 520Z";
        templateArt.silhouetteTopY = 132;
        templateArt.heelTabPathData = "M81 198 65 122 72 108 99 102 112 112 128 188Z";
        templateArt.heelTabMarkPathData = "M80 143 90 126 106 138 108 147 92 135 82 153Z";
        templateArt.upperPanels = new Panel[](1);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 250 120 270 160 340 170 440 0 440Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M300 150 720 290 646 360 286 236Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M720 320 1000 320 1000 460 700 460 690 400Z");
        templateArt.framingPanels[3] = Panel(
            PanelRole.Collar, "M40 60 320 60 300 196 276 182 236 172 170 178 120 186 80 200 40 200Z"
        );
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] =
            Panel(PanelRole.Midsole, "M0 420 300 430 1000 450 1000 600 0 600Z");
        templateArt.solePanels[1] =
            Panel(PanelRole.Outsole, "M0 494 700 496 860 490 1000 470 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M780 352 812 358 772 430 742 430ZM84 230 102 226 96 330 78 332Z";
        templateArt.laceSlatPathData =
            "M324 191 344 199 325 255 304 248ZM384 212 404 219 385 276 364 269ZM444 233 464 240 445 297 424 289ZM504 253 524 261 505 317 484 310ZM564 274 584 281 565 338 544 331ZM624 295 644 302 625 359 604 351Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"014200E7017E00FC01BA011001F601250232013A026E014E";
        templateArt.optionValueCounts = [uint8(3), 4, 3];
    }

    /// @dev Sock: Cuff (Plain, Band, Tipped), Cage (Wrap, Zigzag, Plain, Chevron), Sole (Flat, Stripe, Pod).
    function readSockOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Cuff: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Cuff: Band
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 154 290 136 296 160 40 180Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Cuff: Tipped
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 100 320 100 300 148 40 160Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Cage: Wrap
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M0 200 220 214 340 440 0 440Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Cage: Zigzag
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Overlay,
                "M170 440 170 372 240 404 310 362 380 400 450 358 520 396 590 360 690 400 690 440Z"
            );
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Cage: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 3) {
            // Cage: Chevron
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M200 322 290 322 390 382 290 442 200 442 300 382Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Sole: Flat
            optionValue.layer = OptionLayer.Sole;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Sole: Stripe
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M0 454 860 472 830 482 0 466Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Sole: Pod
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M40 424 300 432 220 494 40 494Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Skate. A skate shoe: a puffy collar, a fat tongue and a flat sole that wraps the toe.
    function readSkateArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M80 520 64 506 60 480 60 440 58 390 62 330 72 280 86 250 108 232 150 228 196 238 236 252 268 252 290 236 300 200 310 160 330 140 372 136 394 150 402 176 404 210 660 320 740 336 820 350 876 366 914 390 934 420 940 452 938 480 930 500 910 514 870 520Z";
        templateArt.silhouetteTopY = 136;
        templateArt.heelTabPathData = "M80 297 55 223 61 209 88 200 101 208 125 283Z";
        templateArt.heelTabMarkPathData = "M73 243 81 224 98 235 101 244 84 234 76 252Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M296 100 440 100 440 220 330 270 296 260Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 220 140 250 170 320 178 450 0 450Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M398 150 720 290 643 360 387 250Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M700 300 1000 300 1000 460 660 460 676 380Z");
        templateArt.framingPanels[3] = Panel(
            PanelRole.Collar,
            "M30 180 312 180 300 240 282 262 240 282 196 274 150 266 108 270 74 290 30 290Z"
        );
        templateArt.solePanels = new Panel[](3);
        templateArt.solePanels[0] = Panel(PanelRole.Midsole, "M0 446 1000 456 1000 600 0 600Z");
        templateArt.solePanels[1] =
            Panel(PanelRole.Midsole, "M900 360 1000 360 1000 470 820 470 850 436Z");
        templateArt.solePanels[2] = Panel(PanelRole.Outsole, "M0 504 1000 504 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M760 344 792 350 750 420 720 420ZM84 300 102 296 96 400 78 402Z";
        templateArt.laceSlatPathData =
            "M424 206 444 214 421 269 401 261ZM475 228 496 236 472 291 452 283ZM527 250 547 258 523 313 503 305ZM578 272 598 280 574 335 554 327ZM629 294 649 302 626 357 605 349Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"01A300F501D7010B020A0121023D01370270014D";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Skate: Side (Shard, Wedge, Plain, Block), Foxing (Plain, Stripe, Double), Heel (Plain, Patch, Counter).
    function readSkateOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Side: Shard
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M178 446 330 290 420 290 268 446Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Side: Wedge
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M178 290 600 450 178 450Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Side: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Side: Block
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M178 370 660 404 660 460 178 460Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Foxing: Plain
            optionValue.layer = OptionLayer.Sole;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Foxing: Stripe
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M0 470 1000 478 1000 494 0 486Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Foxing: Double
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.SoleAccent,
                "M0 462 1000 470 1000 480 0 472ZM0 484 1000 492 1000 502 0 494Z"
            );
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Heel: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Heel: Patch
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M70 300 146 306 150 372 72 372Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Heel: Counter
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 340 150 360 178 450 40 450Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Spike. A track spike: low and pointed, with a spike plate under the forefoot.
    function readSpikeArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M100 516 80 508 70 490 68 460 66 420 70 370 80 320 94 286 120 274 160 278 206 292 244 298 282 286 310 266 324 244 346 230 374 230 388 244 392 258 640 350 720 372 800 388 870 404 920 420 950 436 958 454 950 470 920 482 898 492 880 494 870 520 860 494 820 494 810 520 800 494 760 494 750 520 740 494 700 494 690 520 680 494 640 494 630 520 620 494 560 494 520 498 470 504 400 510 300 514 200 516Z";
        templateArt.silhouetteTopY = 230;
        templateArt.heelTabPathData = "M84 333 66 257 72 243 99 236 112 245 131 321Z";
        templateArt.heelTabMarkPathData = "M82 278 91 260 107 271 110 281 93 270 84 287Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M316 200 440 200 440 280 340 330 316 320Z");
        templateArt.framingPanels = new Panel[](4);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 260 140 280 180 340 186 460 0 460Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M386 204 700 322 625 389 377 297Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M700 340 1000 340 1000 480 670 480 680 410Z");
        templateArt.framingPanels[3] = Panel(
            PanelRole.Collar,
            "M40 230 340 230 330 262 300 290 256 314 206 310 160 300 120 300 84 318 40 318Z"
        );
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] =
            Panel(PanelRole.Midsole, "M0 446 400 460 1000 468 1000 600 0 600Z");
        templateArt.solePanels[1] =
            Panel(PanelRole.Outsole, "M0 504 480 500 1000 482 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M790 384 822 390 790 450 760 450ZM92 330 110 326 102 420 84 422Z";
        templateArt.laceSlatPathData =
            "M411 252 431 260 410 316 390 308ZM460 271 481 278 460 334 439 327ZM510 289 530 297 510 353 489 345ZM559 307 580 315 559 371 539 364ZM609 326 630 333 609 390 588 382Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"0198012401C9013601FB0148022D015B025E016D";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Spike: Side (Dart, Streaks, Plain, Chevron), Support (None, Counter, Strap), Plate (Matched, Contrast, Flash).
    function readSpikeOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Side: Dart
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Overlay, "M186 330 580 400 186 456 260 396Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Side: Streaks
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M186 330 500 380 186 366ZM186 390 600 430 186 430Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Side: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Side: Chevron
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M230 330 320 330 420 390 320 450 230 450 330 390Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Support: None
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Support: Counter
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 360 150 376 186 460 40 460Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Support: Strap
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M304 280 376 300 330 470 256 470Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Plate: Matched
            optionValue.layer = OptionLayer.Sole;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Plate: Contrast
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.SoleAccent, "M500 486 1000 474 1000 600 500 600Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Plate: Flash
            optionValue.layer = OptionLayer.Sole;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.SoleAccent, "M20 466 420 474 400 486 20 480Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }

    /// @dev The Hiker. A mid hiking boot: an ankle shaft, deep lugs and a rubber toe bumper.
    function readHikerArt() private pure returns (TemplateArt memory templateArt) {
        templateArt.silhouettePathData =
            "M128 520 98 512 78 500 66 476 62 440 58 390 60 330 66 260 74 200 86 156 116 140 160 136 206 142 240 152 256 136 274 116 310 110 330 122 338 142 640 320 720 336 800 350 864 366 908 388 934 420 944 456 940 484 926 502 900 512 884 520 830 520 823 500 813 500 806 520 752 520 745 500 735 500 728 520 674 520 667 500 657 500 650 520 596 520 589 500 579 500 572 520 518 520 511 500 501 500 494 520 440 520 433 500 423 500 416 520 362 520 355 500 345 500 338 520 284 520 277 500 267 500 260 520 206 520 199 500 189 500 182 520Z";
        templateArt.silhouetteTopY = 110;
        templateArt.heelTabPathData = "M71 204 58 127 66 113 93 108 105 118 119 195Z";
        templateArt.heelTabMarkPathData = "M73 148 83 131 98 144 100 154 85 141 75 158Z";
        templateArt.upperPanels = new Panel[](2);
        templateArt.upperPanels[0] = Panel(PanelRole.Upper, "M0 0 1000 0 1000 600 0 600Z");
        templateArt.upperPanels[1] =
            Panel(PanelRole.Tongue, "M240 60 380 60 380 170 300 230 240 210Z");
        templateArt.framingPanels = new Panel[](5);
        templateArt.framingPanels[0] =
            Panel(PanelRole.Heel, "M0 300 150 316 200 370 206 440 0 440Z");
        templateArt.framingPanels[1] = Panel(PanelRole.Eyestay, "M334 80 700 290 617 360 315 182Z");
        templateArt.framingPanels[2] =
            Panel(PanelRole.Toe, "M690 310 1000 310 1000 460 670 460 676 390Z");
        templateArt.framingPanels[3] =
            Panel(PanelRole.Trim, "M860 350 1000 350 1000 470 760 470 800 420Z");
        templateArt.framingPanels[4] =
            Panel(PanelRole.Collar, "M30 60 270 60 262 150 236 186 190 184 130 186 80 202 30 202Z");
        templateArt.solePanels = new Panel[](2);
        templateArt.solePanels[0] =
            Panel(PanelRole.Midsole, "M0 420 300 428 1000 446 1000 600 0 600Z");
        templateArt.solePanels[1] =
            Panel(PanelRole.Outsole, "M0 466 700 470 880 466 1000 450 1000 600 0 600Z");
        templateArt.sheenPathData =
        "M770 344 802 350 770 410 740 410ZM84 220 102 216 96 320 78 322Z";
        templateArt.laceSlatPathData =
            "M356 139 375 150 345 202 326 190ZM399 164 418 175 388 227 369 216ZM442 190 461 201 431 253 412 241ZM486 215 505 226 474 278 455 267ZM529 241 548 252 517 303 498 292ZM572 266 591 277 560 329 541 318ZM615 291 634 303 604 354 585 343Z";
        // Each eyelet centre: x, then y, two bytes each.
        templateArt.eyeletCenters = hex"015A00B1018600CB01B100E401DC00FD0207011702320130025D014A";
        templateArt.optionValueCounts = [uint8(4), 3, 3];
    }

    /// @dev Hiker: Shaft (Zigzag, Panel, Plain, Peaks), Rand (None, Heel, Wrap), Collar (Plain, Tipped, Stripe).
    function readHikerOptionValue(uint256 slotIndex, uint256 valueIndex)
        private
        pure
        returns (OptionValueArt memory optionValue)
    {
        if (slotIndex == 0 && valueIndex == 0) {
            // Shaft: Zigzag
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(
                PanelRole.Overlay,
                "M206 450 206 380 270 410 330 370 390 404 450 366 510 400 570 364 640 400 640 450Z"
            );
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 1) {
            // Shaft: Panel
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M0 200 250 180 330 300 206 440 0 440Z");
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 2) {
            // Shaft: Plain
            optionValue.layer = OptionLayer.Quarter;
            return optionValue;
        }
        if (slotIndex == 0 && valueIndex == 3) {
            // Shaft: Peaks
            optionValue.layer = OptionLayer.Quarter;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] =
                Panel(PanelRole.Overlay, "M206 450 300 330 394 450ZM370 450 480 310 590 450Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 0) {
            // Rand: None
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 1) {
            // Rand: Heel
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M40 360 180 380 206 440 40 440Z");
            return optionValue;
        }
        if (slotIndex == 1 && valueIndex == 2) {
            // Rand: Wrap
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M0 392 300 400 1000 418 1000 470 0 470Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 0) {
            // Collar: Plain
            optionValue.layer = OptionLayer.Top;
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 1) {
            // Collar: Tipped
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M30 60 270 60 264 130 236 160 30 168Z");
            return optionValue;
        }
        if (slotIndex == 2 && valueIndex == 2) {
            // Collar: Stripe
            optionValue.layer = OptionLayer.Top;
            optionValue.panels = new Panel[](1);
            optionValue.panels[0] = Panel(PanelRole.Trim, "M30 130 262 110 260 134 30 156Z");
            return optionValue;
        }
        revert InvalidArtIndex();
    }
}
