/**
 * Every error code the API can return. Clients switch on these, never on the
 * human-readable message. Each phase appends the codes it introduces.
 */
export const API_ERROR_CODES = [
  'VALIDATION_FAILED',
  'UNAUTHENTICATED',
  'NOT_FOUND',
  'RATE_LIMITED',
  'INTERNAL_ERROR',
  'INVALID_SIGNATURE',
  'NONCE_EXPIRED',
  'REFRESH_TOKEN_REVOKED',
  'SNEAKER_NOT_OWNED',
  'SNEAKER_OUT_OF_ENERGY',
  'SNEAKER_NEEDS_REPAIR',
  'ACTIVITY_SESSION_ALREADY_ACTIVE',
  'ACTIVITY_SESSION_NOT_ACTIVE',
  'MOCK_LOCATION_DETECTED',
  'INSUFFICIENT_ACTIVITY_DATA',
  'SNEAKER_TRANSFERRED_DURING_SESSION',
  // The Founding Pass (D-043)
  'TURNSTILE_FAILED',
  'EMAIL_CODE_RECENTLY_SENT',
  'EMAIL_SEND_FAILED',
  'EMAIL_CODE_INCORRECT',
  'EMAIL_CODE_EXPIRED',
  'EMAIL_CODE_TOO_MANY_ATTEMPTS',
  'EMAIL_PROOF_INVALID',
  'PASS_MINT_NOT_OPEN',
  'PASS_WAITLIST_WINDOW_ONLY',
  'PASS_ALL_MINTED',
  'PASS_MINT_CLOSED',
  'PASS_EMAIL_ALREADY_USED',
  'PASS_WALLET_ALREADY_USED',
  'PASS_ALREADY_MINTED',
  'PASS_MINT_FAILED',
  'FOUNDING_PASS_REQUIRED',
] as const

export type ApiErrorCode = (typeof API_ERROR_CODES)[number]
