import type { Address } from 'viem'
import type { SupportedChainId } from './monad-chains'

export type StrideMonContractAddresses = {
  sneakerNft: Address
  strideToken: Address
  sneakerGame: Address
  foundingPass: Address
}

/**
 * GENERATED by `bun run chain:export-abis` from `packages/contracts/deployments/`.
 * Do not edit by hand.
 */
export const CONTRACT_ADDRESSES_BY_CHAIN_ID: Partial<
  Record<SupportedChainId, StrideMonContractAddresses>
> = {
  10143: {
    sneakerNft: '0x6BE031Ff15F944c226832b6D0B99C03662b29337',
    strideToken: '0xaa665bB572A1375c624ae0affbCa28bF64D3B7c5',
    sneakerGame: '0x4DD989bc2844cEa9a5eb53b3c52bd86FD6bB8f8D',
    foundingPass: '0xAA2b4891a5057aBafD645986ff5493A4F1027080',
  },
}
