import type { Address } from 'viem'
import type { SupportedChainId } from './monad-chains'

export type StrideMonContractAddresses = {
  sneakerNft: Address
  soleToken: Address
  sneakerGame: Address
}

/**
 * GENERATED by `bun run chain:export-abis` from `packages/contracts/deployments/`.
 * Do not edit by hand.
 */
export const CONTRACT_ADDRESSES_BY_CHAIN_ID: Partial<
  Record<SupportedChainId, StrideMonContractAddresses>
> = {
  10143: {
    sneakerNft: '0x082072B5831009e289FAdd27266e0b8E5B57BDec',
    soleToken: '0xEd340b84E676a4De68a86a3B0d45a86fcE202bb3',
    sneakerGame: '0xc4d59c0625C079332f4762ca0Fdc8e9FE439AEa7',
  },
}
