import type { Address } from 'viem'
import type { SupportedChainId } from './monad-chains'

export type StrideMonContractAddresses = {
  sneakerNft: Address
  strideToken: Address
  sneakerGame: Address
}

/**
 * GENERATED by `bun run chain:export-abis` from `packages/contracts/deployments/`.
 * Do not edit by hand.
 */
export const CONTRACT_ADDRESSES_BY_CHAIN_ID: Partial<
  Record<SupportedChainId, StrideMonContractAddresses>
> = {
  10143: {
    sneakerNft: '0x6A9B08943f60F0bb779Bd229f907f92CB8002062',
    strideToken: '0xf835cd7F9cBf44D76c2d7CE0643B4858437485f3',
    sneakerGame: '0x846cd7B8D213Bf516020f22343A69168B81fDE52',
  },
}
