// GENERATED by `bun run chain:export-abis` from packages/contracts/out. Do not edit.
export const sneakerGameAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "admin",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "sneakerNftAddress",
        "type": "address",
        "internalType": "contract SneakerNft"
      },
      {
        "name": "soleTokenAddress",
        "type": "address",
        "internalType": "contract SoleToken"
      },
      {
        "name": "initialGameConfig",
        "type": "tuple",
        "internalType": "struct GameConfig",
        "components": [
          {
            "name": "maxLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxEnergy",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxDurability",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "starterEfficiency",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "efficiencyGainPerLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "durabilityLossPerMinuteBasisPoints",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "energyRegenerationSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "rewardPerEfficiencyMinuteWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointIncreasePerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "upgradeCostPerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "DEFAULT_ADMIN_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "GAME_SERVER_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PAUSER_ROLE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STARTER_LEVEL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "currentEnergy",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getGameConfig",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct GameConfig",
        "components": [
          {
            "name": "maxLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxEnergy",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxDurability",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "starterEfficiency",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "efficiencyGainPerLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "durabilityLossPerMinuteBasisPoints",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "energyRegenerationSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "rewardPerEfficiencyMinuteWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointIncreasePerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "upgradeCostPerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRoleAdmin",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "grantRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "hasClaimedStarterSneaker",
    "inputs": [
      {
        "name": "player",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "hasClaimed",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSessionSettled",
    "inputs": [
      {
        "name": "sessionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "isSettled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "mintStarterSneaker",
    "inputs": [
      {
        "name": "player",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "pause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "paused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "previewSessionReward",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "activeMinutes",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "rewardAmountWei",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "durabilityLoss",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "rewardedMinutes",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteRepairCost",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "repairCostWei",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteUpgradeCost",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "upgradeCostWei",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "callerConfirmation",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "repair",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "revokeRole",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGameConfig",
    "inputs": [
      {
        "name": "newGameConfig",
        "type": "tuple",
        "internalType": "struct GameConfig",
        "components": [
          {
            "name": "maxLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxEnergy",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxDurability",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "starterEfficiency",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "efficiencyGainPerLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "durabilityLossPerMinuteBasisPoints",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "energyRegenerationSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "rewardPerEfficiencyMinuteWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointIncreasePerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "upgradeCostPerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleSession",
    "inputs": [
      {
        "name": "settlement",
        "type": "tuple",
        "internalType": "struct SessionSettlement",
        "components": [
          {
            "name": "sessionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "player",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "activeMinutes",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "distanceMeters",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "sneakerNft",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract SneakerNft"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "soleToken",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract SoleToken"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unpause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "upgrade",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "GameConfigUpdated",
    "inputs": [
      {
        "name": "config",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct GameConfig",
        "components": [
          {
            "name": "maxLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxEnergy",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxDurability",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "starterEfficiency",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "efficiencyGainPerLevel",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "durabilityLossPerMinuteBasisPoints",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "energyRegenerationSeconds",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "rewardPerEfficiencyMinuteWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "repairCostPerPointIncreasePerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "upgradeCostPerLevelWei",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Paused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleAdminChanged",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "newAdminRole",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleGranted",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RoleRevoked",
    "inputs": [
      {
        "name": "role",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "account",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SessionSettled",
    "inputs": [
      {
        "name": "sessionId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "player",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "rewardedMinutes",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "distanceMeters",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "rewardAmountWei",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "durabilityLoss",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SneakerRepaired",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "durabilityRestored",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "repairCostWei",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SneakerUpgraded",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newLevel",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "newEfficiency",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "upgradeCostWei",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Unpaused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AccessControlBadConfirmation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AccessControlUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "neededRole",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EnforcedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpectedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidGameConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSneakerOwner",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NothingToRepair",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SessionAlreadySettled",
    "inputs": [
      {
        "name": "sessionId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SneakerAtMaxLevel",
    "inputs": [
      {
        "name": "tokenId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "StarterSneakerAlreadyClaimed",
    "inputs": [
      {
        "name": "player",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const
