// Writes the help chatbot's only knowledge (Part 8, D-048) from the help page's own text
// (`website/src/content/help.ts`, D-047), so the chatbot and /help never disagree.
//
//   bun run help:export-knowledge           writes apps/api/src/lib/help-chat/help-knowledge.ts
//   bun run help:export-knowledge --check   exits 1 if that file is out of date
//
// Run it after every change to help.ts, then redeploy the API. The website is not a workspace
// (D-035), so the API never imports it: this script carries the words across.

import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  type HelpAnswer,
  type HelpGuide,
  type HelpLink,
  helpBeforeYouStart,
  helpContactContent,
  helpGuides,
  helpHowItWorks,
  helpLostWalletContent,
  helpNetworkSetupContent,
  helpPlainAnswers,
  helpTroubleshootingGroups,
  listHelpTopicIds,
} from '../website/src/content/help'
import { siteUrl } from '../website/src/content/site'

const repositoryRoot = join(import.meta.dir, '..')
const outputPath = join(repositoryRoot, 'apps/api/src/lib/help-chat/help-knowledge.ts')

function renderLink(link: HelpLink): string {
  if (link.href.startsWith('#')) return `${link.label} (topic ${link.href.slice(1)})`
  if (link.href.startsWith('/')) return `${link.label} (${siteUrl}${link.href})`
  return `${link.label} (${link.href})`
}

function renderSteps(steps: readonly string[]): string[] {
  return steps.map((step, stepIndex) => `${stepIndex + 1}. ${step}`)
}

function renderTopic(topicId: string, title: string, lines: readonly string[]): string {
  return [`[topic ${topicId}] ${title}`, ...lines].join('\n')
}

function renderGuide(guide: HelpGuide): string {
  return renderTopic(guide.id, `Guide: ${guide.title}`, [
    ...(guide.intro === undefined ? [] : [guide.intro]),
    ...renderSteps(guide.steps),
    ...(guide.hasNetworkSetup === true
      ? [
          `${helpNetworkSetupContent.detailsHeading}: ${helpNetworkSetupContent.details
            .map((detail) => `${detail.label} ${detail.value}`)
            .join('; ')}.`,
        ]
      : []),
    ...(guide.note === undefined ? [] : [guide.note]),
    ...(guide.links ?? []).map((link) => `Link: ${renderLink(link)}`),
  ])
}

function renderAnswer(answer: HelpAnswer): string {
  return renderTopic(answer.id, answer.question, [
    ...answer.paragraphs,
    ...renderSteps(answer.steps ?? []),
    ...(answer.links ?? []).map((link) => `Link: ${renderLink(link)}`),
  ])
}

function renderHelpKnowledgeText(): string {
  return [
    renderTopic(
      'how-it-works',
      'How it works',
      helpHowItWorks.map((step, stepIndex) => `${stepIndex + 1}. ${step.title}: ${step.text}`),
    ),
    renderTopic('before-you-start', 'Before you start', [
      ...helpBeforeYouStart.items.map((item) => `- ${item}`),
      helpBeforeYouStart.noMoneyLine,
    ]),
    ...helpGuides.map(renderGuide),
    ...helpPlainAnswers.map(renderAnswer),
    ...helpTroubleshootingGroups.flatMap((group) =>
      group.answers.map((answer) =>
        renderAnswer({ ...answer, question: `${group.heading}: ${answer.question}` }),
      ),
    ),
    renderTopic('lost-wallet', 'Lost your wallet?', [
      ...helpLostWalletContent.paragraphs,
      ...renderSteps(helpLostWalletContent.steps),
      helpLostWalletContent.note,
    ]),
    renderTopic('contact', 'Contact', [
      `${helpContactContent.intro} Email: ${helpContactContent.supportEmail}.`,
      `${helpContactContent.includeHeading}: ${helpContactContent.includeItems.join('; ')}.`,
      helpContactContent.note,
      `${helpContactContent.xPrompt} ${helpContactContent.xAccountHandle} (${helpContactContent.xAccountUrl})`,
    ]),
  ].join('\n\n')
}

function renderModule(): string {
  const topicIds = [...new Set(listHelpTopicIds())]
  return `// Generated by \`bun run help:export-knowledge\` from website/src/content/help.ts (D-047, D-048).
// Never edit it by hand: change help.ts, then run the script again.

/** Every anchor on ${siteUrl}/help. The chatbot may only link to these. */
export const HELP_TOPIC_IDS = ${JSON.stringify(topicIds)} as const

export type HelpTopicId = (typeof HELP_TOPIC_IDS)[number]

/** The help page's text, one \`[topic <id>]\` block per guide and answer. */
export const HELP_KNOWLEDGE_TEXT = ${JSON.stringify(renderHelpKnowledgeText())}
`
}

function formatWithBiome(source: string): string {
  const result = spawnSync('bunx', ['biome', 'format', `--stdin-file-path=${outputPath}`], {
    cwd: repositoryRoot,
    input: source,
    encoding: 'utf8',
  })
  if (result.status !== 0) throw new Error(`biome format failed:\n${result.stderr}`)
  return result.stdout
}

const generatedSource = formatWithBiome(renderModule())

if (process.argv.includes('--check')) {
  let currentSource = ''
  try {
    currentSource = readFileSync(outputPath, 'utf8')
  } catch {
    // Missing counts as out of date.
  }
  if (currentSource !== generatedSource) {
    console.error(
      'apps/api/src/lib/help-chat/help-knowledge.ts is out of date. Run: bun run help:export-knowledge',
    )
    process.exit(1)
  }
  console.log('The help chatbot’s knowledge matches help.ts.')
} else {
  writeFileSync(outputPath, generatedSource)
  console.log(`Wrote ${outputPath}`)
}
