/** The first lines of every generated Solidity file. */
export const GENERATED_FILE_HEADER = [
  '// SPDX-License-Identifier: MIT',
  '// Generated by packages/contracts/art/founding-pass/build-founding-pass-art.ts.',
  '// Never edit it by hand: change the art system (art/founding-pass) and rebuild.',
].join('\n')

/**
 * A Solidity string literal. The art's words and path data are plain ASCII, so anything else
 * (a quote, a backslash, a non-ASCII letter) is a mistake in the art data, not something to escape.
 */
export function quoteSolidityString(text: string): string {
  if (!/^[\x20-\x7E]*$/.test(text) || /["\\]/.test(text)) {
    throw new Error(`Not plain ASCII for a Solidity string: ${text}`)
  }
  return `"${text}"`
}
